name: ginger-anchors
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip>=21.2
  - python>=3.9
  - cudatoolkit=11.3
  - pytorch>=1.10
  - pandas
  - numpy
  - seaborn
  - pytest
  - pip:
    - -r requirements.txt

